[project]
name = "fetcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jaeseung Lee", email = "41176085+tkxkd0159@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
fetcher = "fetcher:main"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"
